name: Sportal-Teleport
version: '${project.version}'
main: sportal.sportalteleport1.SPortal_Teleport_1
api-version: '1.20'

commands:
  tpa:
    description: 'Send a teleport request to another player.'
  tpaccept:
    description: "Accept teleport requests."
  tpdeny:
    description: "Deny teleport requests."
  tpahere:
    description: "Send a request for another player to teleport to you."
  tpcancel:
    description: "Cancel your currently pending teleport request."
